extends Node

const CB = {
		0:{"title": "Test Card TOWER",
			"atk": 20,
			"interval": 1.0,
			"range": 128,
			"canTargetAir": false ,
			"AOE": false,
			"slow":false,
			"dot":false,
			"towerSprite":"res://sprites/towers/temp-tower.png",
			"cardSprite":"res://Assets/Cards/Units/Basic.png",
			"type":"tower",
			"cost":1,
		} ,
		1:{"title": "Test Card FLYING TOWER",
			"atk": 20,
			"interval": 1.0,
			"range": 128,
			"canTargetAir": true ,
			"AOE": false,
			"slow":false,
			"dot":false,
			"towerSprite":"res://sprites/towers/temp-air-tower.png",
			"cardSprite":"res://Assets/Cards/Units/Flying.png",
			"type":"tower",
			"cost":1,
		} ,
		2:{"title": "Test Card AOE TOWER",
			"atk": 10,
			"interval": 2.0,
			"range": 192,
			"canTargetAir": false ,
			"AOE": true,
			"slow":false,
			"dot":false,
			"towerSprite":"res://sprites/towers/temp-aoe-tower.png",
			"cardSprite":"res://Assets/Cards/Units/AOE.png",
			"type":"tower",
			"cost":1,
		} ,
		3:{"title": "Test Card DoT TOWER",
			"atk": 10,
			"interval": 2.0,
			"range": 160,
			"canTargetAir": false ,
			"AOE": false,
			"slow":false,
			"dot":true,
			"towerSprite":"res://sprites/towers/temp-dot-tower.png",
			"cardSprite":"res://Assets/Cards/Units/DoT.png",
			"type":"tower",
			"cost":1,
		} ,
		4:{"title": "Test Card SLOW TOWER",
			"atk": 0,
			"interval": 0,
			"range": 256,
			"canTargetAir": true ,
			"AOE": true,
			"slow":true,
			"dot":false,
			"towerSprite":"res://sprites/towers/temp-slow-tower.png",
			"cardSprite":"res://Assets/Cards/Units/Slow.png",
			"type":"tower",
			"cost":1,
		} ,
		100:{"title": "Test Card Splash",
			"text": "",
			"cardSprite":"",
			"type":"splash",
			"cost":10,
			"scene":"",
			}
	}
